version: '3'
services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: rinko
            MYSQL_USER: docker
            MYSQL_PASSWORD: wK0Ak?ci9p
            MYSQL_ROOT_PASSWORD: wK0Ak?ci9p
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
        - ./db/data:/var/lib/mysql
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./db/sql:/docker-entrypoint-initdb.d
        ports:
        - 13306:3306
        networks:
            - app-net

    app:
        build: ./src
        tty: true
        container_name: app
        command: /usr/sbin/init
        entrypoint: /app/docker-entrypoint.sh
        privileged: true
        links:
            - "mysql"
        networks:
            - app-net
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ./src:/app

networks:
  app-net:
    driver: bridge
