"""empty message

Revision ID: 1157eb13296d
Revises: dc1c4bce61c8
Create Date: 2020-05-04 20:50:33.254269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1157eb13296d'
down_revision = 'dc1c4bce61c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('guild', sa.String(length=64), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.UniqueConstraint('guild')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
