"""empty message

Revision ID: 430b82abf8fc
Revises: e708fe7a19e5
Create Date: 2020-05-05 03:16:31.660525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430b82abf8fc'
down_revision = 'e708fe7a19e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnip',
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turnip')
    # ### end Alembic commands ###
