"""empty message

Revision ID: 46388a85cbef
Revises: 5262da010c83
Create Date: 2020-04-29 07:07:48.117980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46388a85cbef'
down_revision = '5262da010c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('guild', sa.String(length=64), nullable=False),
                    sa.Column('user', sa.String(length=64), nullable=False),
                    sa.Column('text', sa.String(length=300), nullable=False),
                    sa.Column('start_at', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('server_info',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('guild', sa.String(length=64), nullable=False),
                    sa.Column('locale', sa.String(length=8), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('table1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table1',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('guild', mysql.VARCHAR(length=64), nullable=False),
                    sa.Column('user', mysql.VARCHAR(length=64), nullable=False),
                    sa.Column('text', mysql.VARCHAR(length=300), nullable=False),
                    sa.Column('start_at', mysql.DATETIME(), nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.drop_table('server_info')
    op.drop_table('reminder')
    # ### end Alembic commands ###
