"""empty message

Revision ID: 5262da010c83
Revises: 
Create Date: 2020-04-29 06:15:11.112038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5262da010c83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table1',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('guild', sa.String(length=64), nullable=False),
                    sa.Column('user', sa.String(length=64), nullable=False),
                    sa.Column('text', sa.String(length=300), nullable=False),
                    sa.Column('start_at', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table1')
    # ### end Alembic commands ###
