"""empty message

Revision ID: 66dc7b13a74b
Revises: 46388a85cbef
Create Date: 2020-04-29 07:09:42.727345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66dc7b13a74b'
down_revision = '46388a85cbef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'server_info', ['guild'])
    op.drop_column('server_info', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_info', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'server_info', type_='unique')
    # ### end Alembic commands ###
