"""empty message

Revision ID: 6aec78dedcf4
Revises: 9dfdc890c1aa
Create Date: 2020-05-02 08:25:18.351317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aec78dedcf4'
down_revision = '9dfdc890c1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
