"""empty message

Revision ID: 7ad7d9cfc7d4
Revises: c318a62918a4
Create Date: 2020-05-05 04:10:15.037512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad7d9cfc7d4'
down_revision = 'c318a62918a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('buy_date', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'buy_date')
    # ### end Alembic commands ###
