"""empty message

Revision ID: 85e80b707b0b
Revises: ea680381d593
Create Date: 2020-04-30 00:38:08.137577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e80b707b0b'
down_revision = 'ea680381d593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
