"""empty message

Revision ID: 8a44839319fb
Revises: 430b82abf8fc
Create Date: 2020-05-05 03:36:03.398122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a44839319fb'
down_revision = '430b82abf8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
