"""empty message

Revision ID: 9dfdc890c1aa
Revises: 42d1e125fb6e
Create Date: 2020-05-02 07:12:21.101580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfdc890c1aa'
down_revision = '42d1e125fb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_call',
                    sa.Column('guild', sa.String(length=64), nullable=False),
                    sa.Column('7d', sa.Boolean(), nullable=True),
                    sa.Column('1d', sa.Boolean(), nullable=True),
                    sa.Column('12H', sa.Boolean(), nullable=True),
                    sa.Column('6H', sa.Boolean(), nullable=True),
                    sa.Column('3H', sa.Boolean(), nullable=True),
                    sa.Column('2H', sa.Boolean(), nullable=True),
                    sa.Column('1H', sa.Boolean(), nullable=True),
                    sa.Column('30M', sa.Boolean(), nullable=True),
                    sa.Column('10M', sa.Boolean(), nullable=True),
                    sa.Column('0M', sa.Boolean(), nullable=True),
                    sa.UniqueConstraint('guild')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_call')
    # ### end Alembic commands ###
