"""empty message

Revision ID: 9f0c0dbda3ad
Revises: abf55c9028b5
Create Date: 2020-05-01 10:50:31.885309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0c0dbda3ad'
down_revision = 'abf55c9028b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_info', sa.Column('enable_quote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_info', 'enable_quote')
    # ### end Alembic commands ###
