"""empty message

Revision ID: abf55c9028b5
Revises: f721382176b4
Create Date: 2020-04-30 00:59:54.851860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf55c9028b5'
down_revision = 'f721382176b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
