"""empty message

Revision ID: afc3c1cf5d8c
Revises: efe9256ac1b3
Create Date: 2020-05-05 04:41:21.418917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc3c1cf5d8c'
down_revision = 'efe9256ac1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('guild', sa.String(length=64), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('turnip', sa.Integer(), nullable=False),
    sa.Column('buy_at', sa.DateTime(), nullable=False),
    sa.Column('rotten_turnip', sa.Integer(), nullable=False),
    sa.UniqueConstraint('guild')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
