"""empty message

Revision ID: d59db8cd0e89
Revises: afc3c1cf5d8c
Create Date: 2020-05-05 04:50:29.270278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59db8cd0e89'
down_revision = 'afc3c1cf5d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('guild', sa.String(length=64), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    # ### end Alembic commands ###
