"""empty message

Revision ID: dbc9f810fdb5
Revises: 85e80b707b0b
Create Date: 2020-04-30 00:40:42.624965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbc9f810fdb5'
down_revision = '85e80b707b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_info', 'locale',
                    existing_type=mysql.VARCHAR(length=8),
                    nullable=True)
    op.alter_column('server_info', 'prefix',
                    existing_type=mysql.VARCHAR(length=8),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_info', 'prefix',
                    existing_type=mysql.VARCHAR(length=8),
                    nullable=False)
    op.alter_column('server_info', 'locale',
                    existing_type=mysql.VARCHAR(length=8),
                    nullable=False)
    # ### end Alembic commands ###
