"""empty message

Revision ID: dc1c4bce61c8
Revises: 6aec78dedcf4
Create Date: 2020-05-02 08:26:12.180038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1c4bce61c8'
down_revision = '6aec78dedcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_channel',
                    sa.Column('guild', sa.String(length=64), nullable=False),
                    sa.Column('channel', sa.String(length=64), nullable=False),
                    sa.UniqueConstraint('guild')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_channel')
    # ### end Alembic commands ###
