"""empty message

Revision ID: e708fe7a19e5
Revises: 1157eb13296d
Create Date: 2020-05-05 03:01:00.981956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e708fe7a19e5'
down_revision = '1157eb13296d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('turnip', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'turnip')
    # ### end Alembic commands ###
