"""empty message

Revision ID: ea680381d593
Revises: e39a2f27b93f
Create Date: 2020-04-30 00:37:47.144656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea680381d593'
down_revision = 'e39a2f27b93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
