"""empty message

Revision ID: efe9256ac1b3
Revises: 7ad7d9cfc7d4
Create Date: 2020-05-05 04:36:41.960265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe9256ac1b3'
down_revision = '7ad7d9cfc7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('guild', sa.String(length=64), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.UniqueConstraint('guild')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    # ### end Alembic commands ###
