"""empty message

Revision ID: f721382176b4
Revises: dbc9f810fdb5
Create Date: 2020-04-30 00:50:58.114433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f721382176b4'
down_revision = 'dbc9f810fdb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
