CREATE TABLE IF NOT EXISTS `dummy` (
    `guild` VARCHAR(64) NOT NULL,
    `user` VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS `dummy2` (
    `guild` VARCHAR(64) NOT NULL,
    `user` VARCHAR(64) NOT NULL
);
